### ISSUE TITLE
[Feature Request] Print captures on the same line as move

### ISSUE THREAD

**Issue by ghost** [PaulKlinger/watch-leela-train#1]
It'd be very nice if the capture info could be printed beside rather than below the moves.

Current:
 206 (R1)
[board]
1 stones captured!
 207 (T2)

Future: 
 206 (R1) 1 stones captured!
[board]
 207 (T2)

This would keep the terminal go board from jumping around when captures are scrolling off the screen.

**Comment by ghost** [comment]
In the same vein, if passing could be on the same line as other moves, that'll also keep the board stable. It's hard to see which is the new stone if the board shifts.

Current:
 451 (pass)
 452 (T17)
[board]

Future:
 451 (pass) 452 (T17)
[board]

**Comment by PaulKlinger** [comment]
Both fixed in the new version [v0.4](https://github.com/PaulKlinger/watch-leela-train/releases/tag/v0.4)

For passing moves the board is now just printed again.
